#!/bin/bash
set -e
pushd definitions_proto
rm *.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/base_gcmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/c_peer2peer_netmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/clientmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/connectionless_netmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/demo.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_broadcastmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_client_enums.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_clientmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_commonmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_client.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_client_chat.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_client_fantasy.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_client_guild.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_client_match_management.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_client_team.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_client_tournament.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_client_watch.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_common.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_common_bot_script.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_common_league.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_common_match_management.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_msgid.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_gcmessages_server.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_hud_types.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_match_metadata.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_modifiers.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_shared_enums.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/dota_usermessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/econ_gcmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/econ_shared_enums.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/gameevents.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/gametoolevents.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/gcsdk_gcmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/gcsystemmsgs.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/netmessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/network_connection.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/networkbasetypes.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/networksystem_protomessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/steammessages.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/te.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/uifontfile_format.proto
wget https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/Protobufs/usermessages.proto
rm -rf ../generated_proto/*.js;  protoc *.proto --js_out=import_style=commonjs_strict,binary:../generated_proto/
popd